# Default values for hosted-control-planes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cluster:
  name: ''
  baseDomain: ''
  vips:
    api: ''
    ingress: ''

pullSecret:
  secret: ''

sshKey:
  key: ''

release:
  name: '4.18.30'
  channel: stable-4.18
  image: quay.io/openshift-release-dev/ocp-release:4.18.30-multi

nodePool:
  replicas: 3

issuer:
  url: kubernetes.default.svc

hcp:
  enabled: false

storage:
  persistentVolume:
    size: 8Gi
    storageClassName: basic
  type: PersistentVolume

clusterSet:
  enabled: true
  name: default

ha:
  enabled: false

acm:
  enabled: true
