apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-services-rolebinding
  namespace: {{ printf "%s-%s" .Release.Namespace .Release.Name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "10"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: patch-services-role
subjects:
  - kind: ServiceAccount
    name: patch-services-sa
