apiVersion: v1
kind: ConfigMap
metadata:
  name: ose-python-scripts
  namespace: {{ printf "%s-%s" .Release.Namespace .Release.Name }}
data:
  ose_utils.py: |-
{{ tpl ( $.Files.Get "_scripts/ose_utils.py" ) $ | indent 4 }}
  annotate.py: |-
{{ tpl ( $.Files.Get "_scripts/annotate.py" ) $ | indent 4 }}
