# Default values for hosted-control-planes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cluster:
  name: ''
  baseDomain: ''
  vips:
    api: ''
    ingress: ''
