apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "pullsecret-cluster-%s" .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
stringData:
{{ include "hosted-control-planes.secrets.pullSecret" . | nindent 2}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "sshkey-cluster-%s" .Release.Name }}
  namespace: {{ .Release.Namespace }}
stringData:
{{ include "hosted-control-planes.secrets.sshKey" . | nindent 2 }}
